services:
  stock-service:
    container_name: stock-service
    build:
      context: .
      dockerfile: ./StockWebAPI/Dockerfile
    ports:
      - "8080:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ./data-stock:/app/data
        
        
  mail-service:
    container_name: mail-service
    build:
      context: .
      dockerfile: ./MailWebAPI/Dockerfile
    ports:
      - "8081:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ./data-mail:/app/data
    depends_on: 
      stock-service:
        condition: service_started
  