// <auto-generated />
using System;
using MailDataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MailDAL.SQLite.Migrations.Migrations
{
    [DbContext(typeof(MailDbContext))]
    partial class MailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("MailDataAccessLayer.Models.MailSubscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("MailSubscribers");
                });

            modelBuilder.Entity("MailDataAccessLayer.Models.SubscriberPreference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MailSubscriberId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MailSubscriberId");

                    b.ToTable("SubscriberPreferences");
                });

            modelBuilder.Entity("MailDataAccessLayer.Models.SubscriberPreference", b =>
                {
                    b.HasOne("MailDataAccessLayer.Models.MailSubscriber", "MailSubscriber")
                        .WithMany("Preferences")
                        .HasForeignKey("MailSubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailSubscriber");
                });

            modelBuilder.Entity("MailDataAccessLayer.Models.MailSubscriber", b =>
                {
                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
